// Interface words for the interactive courses. Most courses use Indonesian
// buttons and labels; a course with `uiLang: "en"` (English Day) shows the
// whole quiz experience in English. Explanations stay in the content's own
// language either way.

import type { Skill } from "@/lib/course/types";

export type UiLang = "id" | "en";

const id = {
  // Course home
  interactiveCourse: "Kursus Interaktif",
  free: "Gratis",
  loadingCourse: "Memuat kursus...",
  progress: "Progres belajar",
  progressCount: (done: number, total: number, pct: number) => `${done}/${total} modul · ${pct}%`,
  startLearning: "Mulai Belajar",
  continueLearning: "Lanjutkan Belajar",
  freeCourse: "Kursus ini gratis",
  freeCourseHint: "Masuk atau daftar dulu (bisa pakai Google) supaya progres belajarmu tersimpan.",
  signInToStart: "Masuk untuk Mulai",
  unlockAll: "Buka seluruh materi, kuis, dan tryout",
  pretestNow: "Pretest gratis bisa langsung dikerjakan.",
  pretestSignIn: "Masuk dulu untuk mengerjakan pretest gratis.",
  seeSyllabus: "Lihat daftar bab dan materinya di bawah.",
  buy: "Beli",
  comingSoon: "Segera hadir",
  levelLocked: "Modul ini belum dibuka. Pengajar akan membukanya saat kelasnya sudah sampai di topik ini.",
  pretestRow: "cek kemampuan awal sebelum belajar",
  questions: (n: number) => `${n} soal`,
  score: (s: number | null, m: number | null) => `skor ${s}/${m}`,
  bestScore: (s: number | null, m: number | null) => `nilai terbaik ${s}/${m}`,
  secondsPerQuestion: (n: number) => `${n} detik per soal`,
  target: (p: number) => `target ${p}%`,
  passToContinue: (p: number) => `lulus minimal ${p}% untuk lanjut`,
  minutes: (n: number) => `${n} menit`,
  liveSoon: "Live Quiz modul ini akan muncul di sini saat pengajar memulainya.",

  // Lesson
  backToCourse: "Kembali ke Kursus",
  loadingLesson: "Memuat materi...",
  saveFailed: "Gagal menyimpan progres.",
  lessonOf: (i: number, n: number) => `Materi ${i}/${n}`,
  lessonMinutes: (n: number) => `±${n} menit`,
  doneShort: "· sudah selesai ✓",
  doneLong: "Sudah selesai ✓ · boleh dibaca ulang kapan saja",
  previous: "Sebelumnya",
  next: "Lanjut",
  toCheckpoint: "Ke Checkpoint",
  checkpoint: "Checkpoint",
  checkpointTitle: (lesson: string) => `Checkpoint: ${lesson}`,

  // Questions
  tryNow: "Coba sekarang",
  check: "Periksa",
  correctShort: "Tepat!",
  correct: "Benar!",
  notQuite: "Belum tepat.",
  answerIs: "Jawaban:",
  tryAgain: "Coba lagi",
  tryThisAgain: "Coba lagi soal ini 💪",
  gotIt: "Mengerti",
  checkpointDone: "Checkpoint selesai!",
  firstTry: "Benar di percobaan pertama:",
  hots: "🧠 HOTS · Ayo berpikir!",
  answerAria: "Jawaban",
  orderHint: "Ketuk atau seret kata ke sini…",
  matchHint: "Ketuk item kiri lalu pasangannya di kanan (atau seret).",
  tapCards: "Ketuk kartu untuk mendengar cara mengucapkannya.",

  // Audio
  audioUnsupported: "Browser ini tidak mendukung pemutar suara. Gunakan Chrome, Edge, atau Safari versi terbaru.",
  stopAudio: "Hentikan audio",
  playAudio: "Putar audio",
  listening: "Mendengarkan…",
  audioDone: "Audio selesai",
  replay: "Putar ulang",
  playOnce: "Audio hanya bisa diputar satu kali.",
  playingNow: "Sedang memutar",
  chooseAnswer: "Pilih jawaban Anda.",
  useHeadset: "Gunakan headset untuk hasil terbaik.",
  transcript: "Transkrip",

  // Quiz
  questionOf: (i: number, n: number) => `Soal ${i} dari ${n}`,
  timeUp: "Waktu habis",
  secondsLeft: (n: number) => `⏱ ${n} detik`,
  submit: (done: number, total: number) => `Kumpulkan (${done}/${total})`,
  confirmBlank: (n: number) => `Masih ada ${n} soal kosong. Kumpulkan sekarang?`,
  submitFailed: "Gagal mengumpulkan quiz.",
  correctOf: (s: number, m: number) => `${s} dari ${m} benar`,
  pretestDone: "Pretest selesai — materi bab ini sudah terbuka. Yuk mulai belajar!",
  passed: "Lulus! Level berikutnya terbuka.",
  passedOpen: "Mantap, target tercapai!",
  notPassed: (p: number) => `Belum lulus (minimal ${p}%).`,
  belowTarget: (p: number) => `Belum mencapai target ${p}%. Boleh diulang kapan saja.`,
  retryQuiz: "Ulangi Quiz",
  review: "Pembahasan",
  onlyWrong: "Tampilkan hanya yang salah",
  right: "Benar",
  wrong: "Salah",
  unanswered: "Tidak dijawab",
  key: "Kunci:",

  skills: {
    listening: "Listening",
    structure: "Structure",
    reading: "Reading",
    vocabulary: "Kosakata",
    speaking: "Berbicara",
    writing: "Menulis",
  } satisfies Record<Skill, string>,
};

export type UiText = typeof id;

const en: UiText = {
  interactiveCourse: "Interactive Course",
  free: "Free",
  loadingCourse: "Loading the course...",
  progress: "Your progress",
  progressCount: (done, total, pct) => `${done}/${total} items · ${pct}%`,
  startLearning: "Start Learning",
  continueLearning: "Continue Learning",
  freeCourse: "This course is free",
  freeCourseHint: "Sign in or sign up (Google works too) so your progress is saved.",
  signInToStart: "Sign In to Start",
  unlockAll: "Unlock every lesson, quiz and tryout",
  pretestNow: "You can take the free pretest right away.",
  pretestSignIn: "Sign in to take the free pretest.",
  seeSyllabus: "See the modules and lessons below.",
  buy: "Buy",
  comingSoon: "Coming soon",
  levelLocked: "This module isn't open yet. Your teacher will open it when the class reaches this topic.",
  pretestRow: "check your level before you start",
  questions: (n) => `${n} questions`,
  score: (s, m) => `score ${s}/${m}`,
  bestScore: (s, m) => `best score ${s}/${m}`,
  secondsPerQuestion: (n) => `${n} seconds per question`,
  target: (p) => `target ${p}%`,
  passToContinue: (p) => `pass with ${p}% to continue`,
  minutes: (n) => `${n} min`,
  liveSoon: "This module's Live Quiz will appear here when your teacher starts it.",

  backToCourse: "Back to Course",
  loadingLesson: "Loading the lesson...",
  saveFailed: "Couldn't save your progress.",
  lessonOf: (i, n) => `Lesson ${i}/${n}`,
  lessonMinutes: (n) => `±${n} min`,
  doneShort: "· completed ✓",
  doneLong: "Completed ✓ · review it anytime",
  previous: "Back",
  next: "Next",
  toCheckpoint: "Go to Checkpoint",
  checkpoint: "Checkpoint",
  checkpointTitle: (lesson) => `Checkpoint: ${lesson}`,

  tryNow: "Try it",
  check: "Check",
  correctShort: "Correct!",
  correct: "Correct!",
  notQuite: "Not quite.",
  answerIs: "Answer:",
  tryAgain: "Try again",
  tryThisAgain: "Try this one again 💪",
  gotIt: "Got it",
  checkpointDone: "Checkpoint complete!",
  firstTry: "Correct on the first try:",
  hots: "🧠 HOTS · Think it through!",
  answerAria: "Answer",
  orderHint: "Tap or drag the words here…",
  matchHint: "Tap an item on the left, then its match on the right (or drag).",
  tapCards: "Tap a card to hear how to say it.",

  audioUnsupported: "This browser can't play the audio. Please use the latest Chrome, Edge or Safari.",
  stopAudio: "Stop audio",
  playAudio: "Play audio",
  listening: "Listening…",
  audioDone: "Audio finished",
  replay: "Play again",
  playOnce: "The audio plays only once.",
  playingNow: "Playing",
  chooseAnswer: "Choose your answer.",
  useHeadset: "Use headphones for the best sound.",
  transcript: "Transcript",

  questionOf: (i, n) => `Question ${i} of ${n}`,
  timeUp: "Time's up",
  secondsLeft: (n) => `⏱ ${n}s`,
  submit: (done, total) => `Submit (${done}/${total})`,
  confirmBlank: (n) => `${n} question${n === 1 ? " is" : "s are"} still blank. Submit now?`,
  submitFailed: "Couldn't submit the quiz.",
  correctOf: (s, m) => `${s} of ${m} correct`,
  pretestDone: "Pretest done — this chapter is now open. Let's start!",
  passed: "Passed! The next level is open.",
  passedOpen: "Great job — you reached the target!",
  notPassed: (p) => `Not passed yet (you need ${p}%).`,
  belowTarget: (p) => `Below the ${p}% target. You can retry anytime.`,
  retryQuiz: "Retry Quiz",
  review: "Review",
  onlyWrong: "Show only wrong answers",
  right: "Correct",
  wrong: "Wrong",
  unanswered: "Not answered",
  key: "Key:",

  skills: {
    listening: "Listening",
    structure: "Structure",
    reading: "Reading",
    vocabulary: "Vocabulary",
    speaking: "Speaking",
    writing: "Writing",
  },
};

export const UI_TEXT: Record<UiLang, UiText> = { id, en };
